import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*.{js,ts,tsx,mjs,cjs}": "vp check --fix",
    "*.{json,md,css}": "vp fmt",
  },
  lint: {
    ignorePatterns: [
      "**/.next/**",
      "**/.turbo/**",
      "**/dist/**",
      "**/node_modules/**",
      "**/next-env.d.ts",
      "**/.agents/skills/**",
    ],
    plugins: ["typescript", "react", "jsx-a11y", "react-perf", "import"],
    rules: {
      "typescript/consistent-type-imports": "error",
      /** React Doctor Rules */
      "react/rules-of-hooks": "error",
      "react/no-direct-mutation-state": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-key": "error",
      "react/no-children-prop": "warn",
      "react/no-danger": "warn",
      "react/jsx-no-script-url": "error",
      "react/no-render-return-value": "warn",
      "react/no-string-refs": "warn",
      "react/no-is-mounted": "warn",
      "react/require-render-return": "error",
      "react/no-unknown-property": "warn",
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-is-valid": "warn",
      "jsx-a11y/click-events-have-key-events": "warn",
      "jsx-a11y/no-static-element-interactions": "warn",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/no-autofocus": "warn",
      "jsx-a11y/heading-has-content": "warn",
      "jsx-a11y/html-has-lang": "warn",
      "jsx-a11y/no-redundant-roles": "warn",
      "jsx-a11y/scope": "warn",
      "jsx-a11y/tabindex-no-positive": "warn",
      "jsx-a11y/label-has-associated-control": "warn",
      "jsx-a11y/no-distracting-elements": "error",
      "jsx-a11y/iframe-has-title": "warn",
    },
  },
  fmt: {
    ignorePatterns: [
      "**/.next/**",
      "**/.turbo/**",
      "**/dist/**",
      "**/node_modules/**",
      "**/pnpm-lock.yaml",
    ],
    tabWidth: 2,
    singleQuote: false,
    printWidth: 80,
    sortImports: {
      internalPattern: ["@/", "@pookie/"],
      customGroups: [
        { groupName: "react", elementNamePattern: ["react"] },
        { groupName: "next", elementNamePattern: ["next/"] },
        { groupName: "effect", elementNamePattern: ["effect"] },
        { groupName: "components", elementNamePattern: ["@/components/"] },
        { groupName: "hooks", elementNamePattern: ["@/hooks/"] },
        { groupName: "types-pkg", elementNamePattern: ["types"] },
        { groupName: "internal-types", elementNamePattern: ["@/types/"] },
      ],
      groups: [
        "value-builtin",
        "value-external",
        "react",
        "next",
        "effect",
        "components",
        "hooks",
        "value-internal",
        ["value-parent", "value-sibling", "value-index"],
        ["type-builtin", "type-external"],
        ["type-internal", "type-parent", "type-sibling", "type-index"],
        "types-pkg",
        "internal-types",
        "unknown",
      ],
    },
    sortTailwindcss: {},
    sortPackageJson: false,
  },
});
